on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test_options:
        description: 'Test options for the run'
        required: false
        default: '--project=regression'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.BASE_URL }}
        run: |
          example-command "$SUPER_SECRET"
