on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test_options:
        description: 'Test options for the run'
        required: false
        default: '--project=regression'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret (Masked)
        run: echo "Secret is set"
        env:
          SECRET_VALUE: ${{ secrets.BASE_URL }}

